"""app/config/defaults.py — 配置默认值。

所有配置项的默认值集中管理，供：
- 空配置时生成默认配置
- 配置迁移
- 测试
"""

from __future__ import annotations

# ---- API 默认值 ----
DEFAULT_BASE_URL = "https://api.openai.com/v1"
DEFAULT_MODEL = "gpt-4.1-mini"
DEFAULT_API_TIMEOUT_SECONDS = 60

# ---- TTS 默认值 ----
DEFAULT_TTS_ENABLED = False
DEFAULT_TTS_PROVIDER = "none"
DEFAULT_GPT_SOVITS_API_URL = "http://127.0.0.1:9880/tts"
DEFAULT_GPT_SOVITS_REF_LANG = "ja"
DEFAULT_GPT_SOVITS_TEXT_LANG = "ja"
DEFAULT_GPT_SOVITS_TIMEOUT_SECONDS = 60

# ---- 主动关怀默认值 ----
DEFAULT_PROACTIVE_CARE_ENABLED = False
DEFAULT_PROACTIVE_SCREEN_CONTEXT_ENABLED = False
DEFAULT_PROACTIVE_CHECK_INTERVAL_MINUTES = 20
DEFAULT_PROACTIVE_COOLDOWN_MINUTES = 10
DEFAULT_PROACTIVE_SCREEN_CONTEXT_BATCH_LIMIT = 6

# ---- 记忆整理默认值 ----
DEFAULT_MEMORY_CURATION_ENABLED = True
DEFAULT_MEMORY_CURATION_TRIGGER_TURNS = 8
DEFAULT_MEMORY_CURATION_BACKFILL_LIMIT = 200

# ---- MCP 默认值 ----
DEFAULT_WINDOWS_MCP_ENABLED = False

# ---- 调试默认值 ----
DEFAULT_DEBUG_ENABLED = False
DEFAULT_DEBUG_BODY_ENABLED = False

# ---- UI 默认值 ----
DEFAULT_SUBTITLE_LANGUAGE = "ja"
DEFAULT_PORTRAIT_SCALE_PERCENT = 100
DEFAULT_PORTRAIT_SCALE_MIN = 50
DEFAULT_PORTRAIT_SCALE_MAX = 150
DEFAULT_FREE_ACCESS_ENABLED = True

# ---- 角色默认值 ----
DEFAULT_CHARACTER_ID = "sakura"
