from __future__ import annotations

from app.llm.prompts.blocks import (
    AGENT_REPLY_FORMAT,
    DEFAULT_REPLY_PORTRAITS,
    DEFAULT_REPLY_TONES,
    DESKTOP_PET_CONTEXT,
    JSON_ONLY_INSTRUCTION,
    SEGMENTED_REPLY_FORMAT,
    build_proactive_check_segment_rules as _build_proactive_check_segment_rules,
    build_segment_protocol as _build_segment_protocol,
    labels_or_default as _labels_or_default,
    with_desktop_pet_context,
)
from app.llm.prompts.recipes import (
    build_agent_reply_protocol,
    build_context_acquisition_strategy,
    build_event_reply_protocol,
    build_event_system_prompt,
    build_proactive_check_reply_protocol,
    build_proactive_check_tool_system_prompt,
    build_proactive_reply_decision_flow,
    build_proactive_reply_examples,
    build_proactive_rules,
    build_proactive_scene_strategy_rules,
    build_proactive_tool_loop_rules,
    build_proactive_web_research_rules,
    build_segmented_reply_instruction,
)

__all__ = [
    "AGENT_REPLY_FORMAT",
    "DEFAULT_REPLY_PORTRAITS",
    "DEFAULT_REPLY_TONES",
    "DESKTOP_PET_CONTEXT",
    "JSON_ONLY_INSTRUCTION",
    "SEGMENTED_REPLY_FORMAT",
    "build_agent_reply_protocol",
    "build_context_acquisition_strategy",
    "build_event_reply_protocol",
    "build_event_system_prompt",
    "build_proactive_check_reply_protocol",
    "build_proactive_check_tool_system_prompt",
    "build_proactive_reply_decision_flow",
    "build_proactive_reply_examples",
    "build_proactive_rules",
    "build_proactive_scene_strategy_rules",
    "build_proactive_tool_loop_rules",
    "build_proactive_web_research_rules",
    "build_segmented_reply_instruction",
    "with_desktop_pet_context",
]
